### ISSUE TITLE
EDK2 does not compile with gcc 15.2.1

### ISSUE THREAD

**Issue by johnmeneghini** [timberland-sig/edk2#54]
This used to work with `gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)` , however after updating my testbed/platform to Fedora 42 I see:

```
In file included from /home/test/rh-linux-poc/edk2/edk2/NetworkPkg/Library/DxeSpdkLib/SpdkShim/dif_shim.c:9:
/home/test/rh-linux-poc/edk2/edk2/NetworkPkg/Library/DxeSpdkLib/SpdkShim/stdlib_types.h:35:17: error: two or more data types in declaration specifiers
   35 | typedef BOOLEAN bool;
      |                 ^~~~
/home/test/rh-linux-poc/edk2/edk2/NetworkPkg/Library/DxeSpdkLib/SpdkShim/stdlib_types.h:35:1: error: useless type name in empty declaration [-Werror]
   35 | typedef BOOLEAN bool;
      | ^~~~~~~
rm -f /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/SmbiosVersionLib/DetectSmbiosVersionLib/OUTPUT/DetectSmbiosVersionLib.lib
rm -f /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/MicrocodeLib/MicrocodeLib/OUTPUT/MicrocodeLib.lib
"gcc" -MMD -MF /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib/OUTPUT/PeiExtractGuidedSectionLib.obj.deps -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=PeiExtractGuidedSectionLibStrings -m64 -fno-stack-protector "-DEFIAPI=__attribute__((ms_abi))" -maccumulate-outgoing-args -mno-red-zone -Wno-address -mcmodel=small -fpie -fno-asynchronous-unwind-tables -Wno-address -flto -DUSING_LTO -Os -mno-mmx -mno-sse -D DISABLE_NEW_DEPRECATED_INTERFACES -D TDX_GUEST_SUPPORTED -D ENABLE_MD5_DEPRECATED_INTERFACES -c -o /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib/OUTPUT/./PeiExtractGuidedSectionLib.obj -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Library/PeiExtractGuidedSectionLib -I/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib/DEBUG -I/home/test/rh-linux-poc/edk2/edk2/MdePkg -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Test/UnitTest/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include/X64 /home/test/rh-linux-poc/edk2/edk2/MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib.c
"gcc-ar" cr /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/SmbiosVersionLib/DetectSmbiosVersionLib/OUTPUT/DetectSmbiosVersionLib.lib  @/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/SmbiosVersionLib/DetectSmbiosVersionLib/OUTPUT/object_files.lst
"gcc-ar" cr /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/MicrocodeLib/MicrocodeLib/OUTPUT/MicrocodeLib.lib  @/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/MicrocodeLib/MicrocodeLib/OUTPUT/object_files.lst
"gcc" -MMD -MF /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/CpuExceptionHandlerLib/DxeCpuExceptionHandlerLib/OUTPUT/DxeException.obj.deps -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=DxeCpuExceptionHandlerLibStrings -m64 -fno-stack-protector "-DEFIAPI=__attribute__((ms_abi))" -maccumulate-outgoing-args -mno-red-zone -Wno-address -mcmodel=small -fpie -fno-asynchronous-unwind-tables -Wno-address -flto -DUSING_LTO -Os -mno-mmx -mno-sse -D DISABLE_NEW_DEPRECATED_INTERFACES -D TDX_GUEST_SUPPORTED -D ENABLE_MD5_DEPRECATED_INTERFACES -c -o /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/CpuExceptionHandlerLib/DxeCpuExceptionHandlerLib/OUTPUT/./DxeException.obj -I/home/test/rh-linux-poc/edk2/edk2/UefiCpuPkg/Library/CpuExceptionHandlerLib/X64 -I/home/test/rh-linux-poc/edk2/edk2/UefiCpuPkg/Library/CpuExceptionHandlerLib -I/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/CpuExceptionHandlerLib/DxeCpuExceptionHandlerLib/DEBUG -I/home/test/rh-linux-poc/edk2/edk2/MdePkg -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Test/UnitTest/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include/X64 -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/UefiCpuPkg -I/home/test/rh-linux-poc/edk2/edk2/UefiCpuPkg/Include /home/test/rh-linux-poc/edk2/edk2/UefiCpuPkg/Library/CpuExceptionHandlerLib/DxeException.c
Building ... /home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Library/BaseVariableFlashInfoLib/BaseVariableFlashInfoLib.inf [X64]
Trim --asm-file -o /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/CpuExceptionHandlerLib/PeiCpuExceptionHandlerLib/OUTPUT/X64/Xcode5ExceptionHandlerAsm.i -i /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/UefiCpuPkg/Library/CpuExceptionHandlerLib/PeiCpuExceptionHandlerLib/OUTPUT/inc.lst /home/test/rh-linux-poc/edk2/edk2/UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/Xcode5ExceptionHandlerAsm.nasm
"nasm" -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Library/LoadLinuxLib/X64/ -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Library/LoadLinuxLib/X64/ -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Library/LoadLinuxLib/ -I/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LoadLinuxLib/LoadLinuxLib/DEBUG/ -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/ -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include/ -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Test/UnitTest/Include/ -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include/X64/ -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/ -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Include/ -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Csm/Include/ -f elf64 -o /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LoadLinuxLib/LoadLinuxLib/OUTPUT/X64/JumpToKernel.obj /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LoadLinuxLib/LoadLinuxLib/OUTPUT/X64/JumpToKernel.iii
"gcc" -MMD -MF /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/MdeModulePkg/Library/BaseVariableFlashInfoLib/BaseVariableFlashInfoLib/OUTPUT/BaseVariableFlashInfoLib.obj.deps -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=BaseVariableFlashInfoLibStrings -m64 -fno-stack-protector "-DEFIAPI=__attribute__((ms_abi))" -maccumulate-outgoing-args -mno-red-zone -Wno-address -mcmodel=small -fpie -fno-asynchronous-unwind-tables -Wno-address -flto -DUSING_LTO -Os -mno-mmx -mno-sse -D DISABLE_NEW_DEPRECATED_INTERFACES -D TDX_GUEST_SUPPORTED -D ENABLE_MD5_DEPRECATED_INTERFACES -c -o /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/MdeModulePkg/Library/BaseVariableFlashInfoLib/BaseVariableFlashInfoLib/OUTPUT/./BaseVariableFlashInfoLib.obj -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Library/BaseVariableFlashInfoLib -I/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/MdeModulePkg/Library/BaseVariableFlashInfoLib/BaseVariableFlashInfoLib/DEBUG -I/home/test/rh-linux-poc/edk2/edk2/MdePkg -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Test/UnitTest/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include/X64 -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/brotli/c/include /home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Library/BaseVariableFlashInfoLib/BaseVariableFlashInfoLib.c
rm -f /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib/OUTPUT/PlatformBootManagerLib.lib
rm -f /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LoadLinuxLib/LoadLinuxLib/OUTPUT/LoadLinuxLib.lib
"gcc-ar" cr /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib/OUTPUT/PlatformBootManagerLib.lib  @/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib/OUTPUT/object_files.lst
"gcc-ar" cr /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LoadLinuxLib/LoadLinuxLib/OUTPUT/LoadLinuxLib.lib  @/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LoadLinuxLib/LoadLinuxLib/OUTPUT/object_files.lst
Building ... /home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Library/LockBoxLib/LockBoxBaseLib.inf [X64]
"gcc" -MMD -MF /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LockBoxLib/LockBoxBaseLib/OUTPUT/LockBoxBase.obj.deps -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=LockBoxBaseLibStrings -m64 -fno-stack-protector "-DEFIAPI=__attribute__((ms_abi))" -maccumulate-outgoing-args -mno-red-zone -Wno-address -mcmodel=small -fpie -fno-asynchronous-unwind-tables -Wno-address -flto -DUSING_LTO -Os -mno-mmx -mno-sse -D DISABLE_NEW_DEPRECATED_INTERFACES -D TDX_GUEST_SUPPORTED -D ENABLE_MD5_DEPRECATED_INTERFACES -c -o /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LockBoxLib/LockBoxBaseLib/OUTPUT/./LockBoxBase.obj -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Library/LockBoxLib -I/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/OvmfPkg/Library/LockBoxLib/LockBoxBaseLib/DEBUG -I/home/test/rh-linux-poc/edk2/edk2/MdePkg -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Test/UnitTest/Include -I/home/test/rh-linux-poc/edk2/edk2/MdePkg/Include/X64 -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg -I/home/test/rh-linux-poc/edk2/edk2/MdeModulePkg/Include -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Include -I/home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Csm/Include /home/test/rh-linux-poc/edk2/edk2/OvmfPkg/Library/LockBoxLib/LockBoxBase.c
cc1: all warnings being treated as errors
make: *** [GNUmakefile:357: /home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/NetworkPkg/Library/DxeSpdkLib/DxeSpdkLib/OUTPUT/SpdkShim/dif_shim.obj] Error 1


build.py...
 : error 7000: Failed to execute command
        make tbuild [/home/test/rh-linux-poc/edk2/edk2/Build/OvmfX64/DEBUG_GCC5/X64/NetworkPkg/Library/DxeSpdkLib/DxeSpdkLib]


build.py...
 : error F002: Failed to build module
        /home/test/rh-linux-poc/edk2/edk2/NetworkPkg/Library/DxeSpdkLib/DxeSpdkLib.inf [X64, GCC5, DEBUG]

- Failed -
Build end time: 19:19:12, Sep.02 2025
Build total time: 00:00:07

cp: cannot stat 'Build/OvmfX64/DEBUG_GCC5/FV/OVMF_CODE.fd': No such file or directory
cp: cannot stat 'Build/OvmfX64/DEBUG_GCC5/FV/OVMF_VARS.fd': No such file or directory
cp: cannot stat 'Build/OvmfX64/DEBUG_GCC5/FV/OVMF_VARS.fd': No such file or directory
cp: cannot stat 'Build/OvmfX64/DEBUG_GCC5/X64/VConfig.efi': No such file or directory
cp: cannot stat 'Build/OvmfX64/DEBUG_GCC5/X64/NvmeOfCli.efi': No such file or directory
~/rh-linux-poc ~/rh-linux-poc
rhel-storage-109:rh-linux-poc(iso_boot2) > 

rhel-storage-109:rh-linux-poc(iso_boot2) > gcc --version
gcc (GCC) 15.2.1 20250808 (Red Hat 15.2.1-1)
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by johnmeneghini** [comment]
[edk2_build2.log](https://github.com/user-attachments/files/22105950/edk2_build2.log)

**Comment by johnmeneghini** [comment]
@trevor-cockrell did something change in the way we are building these artifacts?    

The method I use can be seen here: https://github.com/timberland-sig/rh-linux-poc/blob/616f2586d74bbf5632226db9d99a5f00f8866171/setup.sh#L251

With an updated tool chain on my Fedora 42 platform, I am no longer able to get the above script to successfully compile and build the artifacts.  See the attached log file.

**Comment by johnmeneghini** [comment]
Looking closely at the log file, it appears the first fatal error is here:

```
make -C VfrCompile VfrLexer.h
make[2]: Entering directory '/home/test/rh-linux-poc/edk2/edk2/BaseTools/Source/C/VfrCompile'
BIN_DIR='.' make -C Pccts/dlg
make[3]: Entering directory '/home/test/rh-linux-poc/edk2/edk2/BaseTools/Source/C/VfrCompile/Pccts/dlg'
cc -O -I. -I../support/set -I../h -DUSER_ZZSYN -DZZLEXBUFSIZE=65536 -c dlg_p.c
cc -O -I. -I../support/set -I../h -DUSER_ZZSYN -DZZLEXBUFSIZE=65536 -c dlg_a.c
cc -O -I. -I../support/set -I../h -DUSER_ZZSYN -DZZLEXBUFSIZE=65536 -c main.c
main.c: In function ‘ProcessArgs’:
main.c:163:42: error: too many arguments to function ‘p->process’; expected 0, have 2
  163 |                                         (*p->process)( *argv, *(argv+1) );
      |                                         ~^~~~~~~~~~~~  ~~~~~
main.c:120:34: note: declared here
  120 |                         WildFunc process;
      |                                  ^~~~~~~
main.c:168:42: error: too many arguments to function ‘p->process’; expected 0, have 1
  168 |                                         (*p->process)( *argv );
      |                                         ~^~~~~~~~~~~~  ~~~~~
main.c:120:34: note: declared here
  120 |                         WildFunc process;
      |                                  ^~~~~~~
make[3]: *** [makefile:151: main.o] Error 1
make[3]: Leaving directory '/home/test/rh-linux-poc/edk2/edk2/BaseTools/Source/C/VfrCompile/Pccts/dlg'
make[2]: *** [GNUmakefile:60: Pccts/dlg/dlg] Error 2
make[2]: Leaving directory '/home/test/rh-linux-poc/edk2/edk2/BaseTools/Source/C/VfrCompile'
make[1]: *** [GNUmakefile:86: VfrCompile/VfrLexer.h] Error 2
make[1]: Leaving directory '/home/test/rh-linux-poc/edk2/edk2/BaseTools/Source/C'
make: *** [GNUmakefile:19: Source/C] Error 2
make: Leaving directory '/home/test/rh-linux-poc/edk2/edk2/BaseTools'
```

**Comment by tbzatek** [comment]
See https://github.com/timberland-sig/edk2/pull/39#pullrequestreview-3164549298 and https://github.com/timberland-sig/edk2/pull/39#issuecomment-3233234911. Instead of backporting any changes, the Timberland working branch should be rebased to edk2/master which compiles fine.
